#!/bin/sh

# uci set luci.main.lang=zh_cn
# uci set luci.main.mediaurlbase=/luci-static/argon
# uci commit luci

# @wifi-iface[0] 表示2.4G网络；@wifi-iface[1] 表示5G网络
# uci set wireless.@wifi-iface[0].ssid='OperWrt'
uci set wireless.@wifi-iface[0].encryption='WPA1WPA2'
uci set wireless.@wifi-iface[0].key='password'
# uci set wireless.@wifi-iface[1].ssid='OperWrt'
uci set wireless.@wifi-iface[1].encryption='WPA1WPA2'
uci set wireless.@wifi-iface[1].key='password'
uci commit wireless

sed -i 's/root:.*/root:$1$PgqmDetr$xqXbP57ysPKh9m36oycQS\/:18361:0:99999:7:::/g' /etc/shadow

# uci set wireless.encryption="WPA/WPA2"
# uci set wireless.key="password"
# uci commit wireless






exit 0
